            - name: Profile Readme Development Stats
  # You may pin to the exact commit or the version.
  # uses: anmol098/waka-readme-stats@6461370353adf9f5bb9c3e909c04fa518f1ff166
  uses: anmol098/waka-readme-stats@V1.1
  with:
    # GitHub access token with Repo scope
    GH_TOKEN: # default is ${{ github.token }}
    # Your Wakatime API Key
    WAKATIME_API_KEY: waka_b9b99e56-b09d-49bc-b406-bd314645e1da
    # Show the list of OS Worked on In dev metrics
    SHOW_OS: # optional, default is True
    # Show the list of projects worked on in dev metrics
    SHOW_PROJECTS: # optional, default is True
    # Show the Editors used in dev metrics
    SHOW_EDITORS: # optional, default is True
    # Show the time zone in the dev metrics
    SHOW_TIMEZONE: # optional, default is True
    # Shows the number of commit graph in the dev metrics
    SHOW_COMMIT: # optional, default is True
    # Show the Coding language used in dev metrics
    SHOW_LANGUAGE: # optional, default is True
    # Show the Total Lines of code written Badge till date
    SHOW_LINES_OF_CODE: # optional, default is False
    # Show language or framework used across different repository
    SHOW_LANGUAGE_PER_REPO: # optional, default is True
    # 
    SHOW_LOC_CHART: # optional, default is True
    # show day of week you are most productive
    SHOW_DAYS_OF_WEEK: # optional, default is True
          
